Repository OCA/l10n-switzerland, pull requests merged in 2021-01, with the labels that each got.

#582 [10.0] Fix l10n ch QR-IBAN validation
  l10n_ch_qr_bill/models/res_bank.py
Labels: approved, bot is merging ⏳

#580 [12.0] l10n_ch_payment_slip hide core "ISR Print" button
  l10n_ch_payment_slip/views/account_invoice.xml
Labels: bot is merging ⏳

#578 [13.0] [ADD] add patch module l10n_ch_isrb
  l10n_ch_isrb/README.rst
  l10n_ch_isrb/__init__.py
  l10n_ch_isrb/__manifest__.py
  l10n_ch_isrb/models/__init__.py
  l10n_ch_isrb/models/account_invoice.py
  l10n_ch_isrb/models/res_partner_bank.py
  l10n_ch_isrb/readme/DESCRIPTION.rst
  l10n_ch_isrb/tests/__init__.py
  l10n_ch_isrb/tests/test_gen_isr_reference.py
  l10n_ch_isrb/views/res_partner_bank.xml
  setup/l10n_ch_isrb/odoo/addons/l10n_ch_isrb
  setup/l10n_ch_isrb/setup.py
Labels: bot is merging ⏳

#576 12.0 add QRR pain001
  l10n_ch_pain_base/models/account_move_line.py
  l10n_ch_pain_base/models/account_payment_line.py
  l10n_ch_pain_base/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#574 [12.0] [ADD] l10n_ch_fix_isr_reference
  l10n_ch_fix_isr_reference/__init__.py
  l10n_ch_fix_isr_reference/__manifest__.py
  l10n_ch_fix_isr_reference/models/__init__.py
  l10n_ch_fix_isr_reference/models/invoice.py
  l10n_ch_payment_slip/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#581 [13.0] Add l10n_ch_invoice_reports module
  l10n_ch_invoice_reports/README.rst
  l10n_ch_invoice_reports/__init__.py
  l10n_ch_invoice_reports/__manifest__.py
  l10n_ch_invoice_reports/controllers/__init__.py
  l10n_ch_invoice_reports/controllers/portal.py
  l10n_ch_invoice_reports/data/reports.xml
  l10n_ch_invoice_reports/models/__init__.py
  l10n_ch_invoice_reports/models/report.py
  l10n_ch_invoice_reports/readme/CONTRIBUTORS.rst
  l10n_ch_invoice_reports/readme/DESCRIPTION.rst
  l10n_ch_invoice_reports/readme/USAGE.rst
  l10n_ch_invoice_reports/static/description/index.html
  setup/l10n_ch_invoice_reports/odoo/addons/l10n_ch_invoice_reports
  setup/l10n_ch_invoice_reports/setup.py
Labels: approved, bot is merging ⏳, ready to merge
