Repository OCA/l10n-switzerland, pull requests merged in 2021-02, with the labels that each got.

#583 [FIX][l10n_ch_invoice_reports] wrong report ID to download
  l10n_ch_invoice_reports/controllers/portal.py
Labels: bot is merging ⏳

#587 [FIX] fix wrong prefix for tag xml_id
  l10n_ch_mis_reports/data/mis.report.kpi.csv
Labels: bot is merging ⏳

#584 [FIX] Check presence of QR IBAN before checking validity
  l10n_ch_qr_bill/models/res_bank.py
Labels: approved, bot is merging ⏳

#562 [8.0][MIG] l10n_ch_qr_bill
  l10n_ch_qr_bill/README.rst
  l10n_ch_qr_bill/__init__.py
  l10n_ch_qr_bill/__openerp__.py
  l10n_ch_qr_bill/controllers/__init__.py
  l10n_ch_qr_bill/controllers/main.py
  l10n_ch_qr_bill/data/paperformat.xml
  l10n_ch_qr_bill/i18n/de.po
  l10n_ch_qr_bill/i18n/fr.po
  l10n_ch_qr_bill/i18n/it.po
  l10n_ch_qr_bill/i18n/l10n_ch_qr_bill.pot
  l10n_ch_qr_bill/models/__init__.py
  l10n_ch_qr_bill/models/account_invoice.py
  l10n_ch_qr_bill/models/report.py
  l10n_ch_qr_bill/models/res_bank.py
  l10n_ch_qr_bill/report/swissqr_report.xml
  l10n_ch_qr_bill/static/description/icon.png
  l10n_ch_qr_bill/static/src/css/report_swissqr.css
  l10n_ch_qr_bill/static/src/img/CH-Cross_7mm.png
  l10n_ch_qr_bill/tests/__init__.py
  l10n_ch_qr_bill/tests/test_swissqr.py
  l10n_ch_qr_bill/views/account_invoice_view.xml
Labels: approved

#556 [ADD] l10n_ch_qr_bill_transaction_id - glue module
  l10n_ch_qr_bill/models/account_invoice.py
  l10n_ch_qr_bill_transaction_id/README.rst
  l10n_ch_qr_bill_transaction_id/__init__.py
  l10n_ch_qr_bill_transaction_id/__manifest__.py
  l10n_ch_qr_bill_transaction_id/models/__init__.py
  l10n_ch_qr_bill_transaction_id/models/account_invoice.py
  l10n_ch_qr_bill_transaction_id/tests/__init__.py
  l10n_ch_qr_bill_transaction_id/tests/test_transaction_id.py
Labels: bot is merging ⏳

#590 [14.0][MIG] l10n_ch_base_bank
  l10n_ch_base_bank/README.rst
  l10n_ch_base_bank/__init__.py
  l10n_ch_base_bank/__manifest__.py
  l10n_ch_base_bank/i18n/de.po
  l10n_ch_base_bank/i18n/fr.po
  l10n_ch_base_bank/i18n/it.po
  l10n_ch_base_bank/i18n/l10n_ch_base_bank.pot
  l10n_ch_base_bank/models/__init__.py
  l10n_ch_base_bank/models/bank.py
  l10n_ch_base_bank/models/invoice.py
  l10n_ch_base_bank/models/partner_bank.py
  l10n_ch_base_bank/postfinance.py
  l10n_ch_base_bank/readme/CONTRIBUTORS.rst
  l10n_ch_base_bank/readme/CREDITS.rst
  l10n_ch_base_bank/readme/DESCRIPTION.rst
  l10n_ch_base_bank/readme/USAGE.rst
  l10n_ch_base_bank/static/description/icon.png
  l10n_ch_base_bank/static/description/index.html
  l10n_ch_base_bank/tests/__init__.py
  l10n_ch_base_bank/tests/test_bank.py
  l10n_ch_base_bank/tests/test_bank_type.py
  l10n_ch_base_bank/tests/test_create_invoice.py
  l10n_ch_base_bank/tests/test_search_invoice.py
  l10n_ch_base_bank/views/bank.xml
  setup/l10n_ch_base_bank/odoo/addons/l10n_ch_base_bank
  setup/l10n_ch_base_bank/setup.py
Labels: bot is merging ⏳

#594 [10.0] Fix _is_qr_iban check
  l10n_ch_qr_bill/models/res_bank.py
  l10n_ch_qr_bill/tests/__init__.py
  l10n_ch_qr_bill/tests/test_is_qr_iban.py
Labels: bot is merging ⏳
