Repository OCA/l10n-switzerland, pull requests merged in 2022-07, with the labels that each got.

#650 [14.0] Restrict number of order ref in ebill_paynet message
  ebill_paynet/__manifest__.py
  ebill_paynet/messages/invoice-2003A.jinja
  ebill_paynet/messages/invoice-2013A.jinja
  ebill_paynet/models/paynet_invoice_message.py
  ebill_paynet/tests/common.py
  ebill_paynet/tests/examples/invoice_isr_b2b.xml
  ebill_paynet/tests/examples/invoice_qr_b2b.xml
  ebill_paynet_customer_free_ref/tests/examples/invoice_b2b.xml
Labels: approved, ready to merge, bot is merging ⏳

#640 [14.0][FIX] tests of l10n_ch_isr_payment_grouping and l10n_ch_base_bank modules
  l10n_ch_base_bank/tests/test_create_invoice.py
  l10n_ch_isr_payment_grouping/tests/test_l10n_ch_payment_isr.py
Labels: bot is merging ⏳

#637 [14.0][MIG] l10n_ch_delivery_carrier_label_quickpac: Migrate to version 14.0
  l10n_ch_delivery_carrier_label_quickpac/README.rst
  l10n_ch_delivery_carrier_label_quickpac/__init__.py
  l10n_ch_delivery_carrier_label_quickpac/__manifest__.py
  l10n_ch_delivery_carrier_label_quickpac/data/delivery.xml
  l10n_ch_delivery_carrier_label_quickpac/data/delivery_option.xml
  l10n_ch_delivery_carrier_label_quickpac/data/delivery_template_option.xml
  l10n_ch_delivery_carrier_label_quickpac/data/partner.xml
  l10n_ch_delivery_carrier_label_quickpac/data/product.xml
  l10n_ch_delivery_carrier_label_quickpac/models/__init__.py
  l10n_ch_delivery_carrier_label_quickpac/models/company.py
  l10n_ch_delivery_carrier_label_quickpac/models/delivery.py
  l10n_ch_delivery_carrier_label_quickpac/models/res_config_settings.py
  l10n_ch_delivery_carrier_label_quickpac/models/stock.py
  l10n_ch_delivery_carrier_label_quickpac/quickpac/__init__.py
  l10n_ch_delivery_carrier_label_quickpac/quickpac/helpers.py
  l10n_ch_delivery_carrier_label_quickpac/quickpac/web_service.py
  l10n_ch_delivery_carrier_label_quickpac/readme/CONFIGURE.rst
  l10n_ch_delivery_carrier_label_quickpac/readme/CONTRIBUTORS.rst
  l10n_ch_delivery_carrier_label_quickpac/readme/CREDITS.rst
  l10n_ch_delivery_carrier_label_quickpac/readme/DESCRIPTION.rst
  l10n_ch_delivery_carrier_label_quickpac/readme/INSTALL.rst
  l10n_ch_delivery_carrier_label_quickpac/static/description/icon.svg
  l10n_ch_delivery_carrier_label_quickpac/static/description/index.html
  l10n_ch_delivery_carrier_label_quickpac/static/img/quickpac-logo.jpg
  l10n_ch_delivery_carrier_label_quickpac/tests/__init__.py
  l10n_ch_delivery_carrier_label_quickpac/tests/fixtures/cassettes/test_invalid_zipcode.yaml
  l10n_ch_delivery_carrier_label_quickpac/tests/fixtures/cassettes/test_store_label.yaml
  l10n_ch_delivery_carrier_label_quickpac/tests/fixtures/cassettes/test_valid_zipcode.yaml
  l10n_ch_delivery_carrier_label_quickpac/tests/test_delivery.py
  l10n_ch_delivery_carrier_label_quickpac/tests/test_quickpac.py
  l10n_ch_delivery_carrier_label_quickpac/views/delivery.xml
  l10n_ch_delivery_carrier_label_quickpac/views/res_config.xml
  requirements.txt
  setup/l10n_ch_delivery_carrier_label_quickpac/odoo/addons/l10n_ch_delivery_carrier_label_quickpac
  setup/l10n_ch_delivery_carrier_label_quickpac/setup.py
Labels: bot is merging ⏳

#644 [14.0][FW] [13.0][IMP] ebill_paynet: round taxes
  ebill_paynet/messages/invoice-2003A.jinja
  ebill_paynet/messages/invoice-2013A.jinja
  ebill_paynet/models/account_invoice.py
  ebill_paynet/tests/examples/invoice_qr_b2b_rounded.xml
  ebill_paynet/tests/test_invoice_message_b2b.py
Labels: approved, ready to merge, bot is merging ⏳

#648 [14.0] Fix ebill_paynet renamed invoice_partner_bank_id
  ebill_paynet/models/account_invoice.py
Labels: bot is merging ⏳, stale
